// Local translation loader for gt-next.
//
// Its presence flips gt-next to loadTranslationsType: 'custom', which stops the
// library from fetching the translation bundle from the General Translation CDN
// during build/runtime. That remote fetch hangs the production build (SSG) on
// platforms that build with a single worker (e.g. Vercel) when no GT project /
// credentials are reachable, freezing at "Generating static pages (0/N)".
//
// Returning an empty map makes gt-next fall back to the source-locale strings
// declared in each <T> component, so the app builds and runs with no live GT
// connection. To ship real translations, import per-locale JSON generated by
// `gtx-cli translate` here instead of returning {}.
export default async function loadTranslations(
  _locale: string,
): Promise<Record<string, string>> {
  return {};
}
