import type { Opportunity } from './types';

export const mockOpportunities: readonly Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Via Torino portfolio',
    company: 'Casa Alto',
    contactName: 'Alessandro Dodi',
    contactInitials: 'AD',
    owner: 'Giulia',
    amount: 100000,
    updatedAt: 'Updated 1h ago',
    stage: 'qualified',
  },
  {
    id: 'opp-2',
    title: 'Green district resale',
    company: 'Conti Realty',
    contactName: 'Elena Conti',
    contactInitials: 'EC',
    owner: 'Davide',
    amount: 84000,
    updatedAt: 'Updated 3h ago',
    stage: 'qualified',
  },
  {
    id: 'opp-3',
    title: 'Riva expansion mandate',
    company: 'Riva Partners',
    contactName: 'Marta Riva',
    contactInitials: 'MR',
    owner: 'Tommaso',
    amount: 132000,
    updatedAt: 'Updated yesterday',
    stage: 'proposal',
  },
  {
    id: 'opp-4',
    title: 'Bellini HQ acquisition',
    company: 'Bellini Assets',
    contactName: 'Francesco Bellini',
    contactInitials: 'FB',
    owner: 'Giulia',
    amount: 215000,
    updatedAt: 'Updated yesterday',
    stage: 'proposal',
  },
  {
    id: 'opp-5',
    title: 'Leone asset rotation',
    company: 'Leone Capital',
    contactName: 'Sara Leone',
    contactInitials: 'SL',
    owner: 'Davide',
    amount: 176000,
    updatedAt: 'Closed this week',
    stage: 'won',
  },
  {
    id: 'opp-6',
    title: 'Neri atelier relocation',
    company: 'Neri Studio',
    contactName: 'Luca Neri',
    contactInitials: 'LN',
    owner: 'Tommaso',
    amount: 58000,
    updatedAt: 'Closed last week',
    stage: 'lost',
  },
] as const;
