import type { Person } from './types';

export const mockPeople: readonly Person[] = [
  {
    id: 'person-1',
    name: 'Alessandro Dodi',
    email: 'alessandro@casaalto.it',
    company: 'Casa Alto',
    title: 'Founder',
    city: 'Milan',
    owner: 'Giulia',
    status: 'active buyer',
    lastContact: '2 hours ago',
    openOpportunities: 2,
    estimatedValue: 184000,
  },
  {
    id: 'person-2',
    name: 'Marta Riva',
    email: 'marta@rivapartners.com',
    company: 'Riva Partners',
    title: 'Operations Lead',
    city: 'Turin',
    owner: 'Tommaso',
    status: 'nurturing',
    lastContact: 'Yesterday',
    openOpportunities: 1,
    estimatedValue: 72000,
  },
  {
    id: 'person-3',
    name: 'Francesco Bellini',
    email: 'francesco@belliniassets.it',
    company: 'Bellini Assets',
    title: 'Managing Director',
    city: 'Rome',
    owner: 'Giulia',
    status: 'champion',
    lastContact: '3 days ago',
    openOpportunities: 3,
    estimatedValue: 265000,
  },
  {
    id: 'person-4',
    name: 'Elena Conti',
    email: 'elena@contirealty.com',
    company: 'Conti Realty',
    title: 'Broker Partner',
    city: 'Bologna',
    owner: 'Davide',
    status: 'active buyer',
    lastContact: 'Today',
    openOpportunities: 1,
    estimatedValue: 93000,
  },
  {
    id: 'person-5',
    name: 'Luca Neri',
    email: 'luca@neristudio.it',
    company: 'Neri Studio',
    title: 'Principal',
    city: 'Florence',
    owner: 'Tommaso',
    status: 'at risk',
    lastContact: '1 week ago',
    openOpportunities: 1,
    estimatedValue: 58000,
  },
  {
    id: 'person-6',
    name: 'Sara Leone',
    email: 'sara@leonecapital.io',
    company: 'Leone Capital',
    title: 'Investment Manager',
    city: 'Naples',
    owner: 'Davide',
    status: 'champion',
    lastContact: '4 hours ago',
    openOpportunities: 2,
    estimatedValue: 141000,
  },
] as const;
