import type { Opportunity } from './types';

export const mockOpportunities: readonly Opportunity[] = [
  {
    id: 'opp-1',
    title: 'Opportunity 1',
    company: 'Studio Alpha',
    contactName: 'Alessandro Dodi',
    contactInitials: 'AD',
    owner: 'Giulia',
    amount: 100000,
    updatedAt: '1h ago',
    stage: 'qualified',
  },
  {
    id: 'opp-2',
    title: 'Opportunity 2',
    company: 'Studio Beta',
    contactName: 'Elena Conti',
    contactInitials: 'EC',
    owner: 'Davide',
    amount: 84000,
    updatedAt: '3h ago',
    stage: 'qualified',
  },
  {
    id: 'opp-3',
    title: 'Opportunity 3',
    company: 'Northwind',
    contactName: 'Marta Riva',
    contactInitials: 'MR',
    owner: 'Tommaso',
    amount: 132000,
    updatedAt: 'Yesterday',
    stage: 'proposal',
  },
  {
    id: 'opp-4',
    title: 'Opportunity 4',
    company: 'Atelier Uno',
    contactName: 'Francesco Bellini',
    contactInitials: 'FB',
    owner: 'Giulia',
    amount: 215000,
    updatedAt: 'Yesterday',
    stage: 'proposal',
  },
  {
    id: 'opp-5',
    title: 'Opportunity 5',
    company: 'Linea Group',
    contactName: 'Sara Leone',
    contactInitials: 'SL',
    owner: 'Davide',
    amount: 176000,
    updatedAt: 'This week',
    stage: 'won',
  },
  {
    id: 'opp-6',
    title: 'Opportunity 6',
    company: 'Studio Delta',
    contactName: 'Luca Neri',
    contactInitials: 'LN',
    owner: 'Tommaso',
    amount: 58000,
    updatedAt: 'Last week',
    stage: 'lost',
  },
] as const;
